version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
BeforeInstall:
  - location: Script/before_script.sh
    timeout: 300
    runas: root
ApplicationStop:
  - location: Script/after_script.sh
    timeout: 300
    runas: root
